### ISSUE TITLE
Suggesting to include an architecture diagram

### ISSUE THREAD

**Issue by lakindu95** [scorelab/Stackle#116]
## Type of issue:
- [ ] Bug / Error
- [ ] Idea / Feature
- [x] Improvement detail

## Short description on the issue
In the readme, under architecture section, better to add an architecture diagram rather than explaining the architecture in words
## Possible fix
Adding an architecture diagram to the readme

**Comment by lakindu95** [comment]
![stackle architecture](https://user-images.githubusercontent.com/19621902/37521164-bbc81edc-2945-11e8-92ff-bffc0988131e.jpg)

@psnmissaka how about this high level diagram? Any alternations to do?

**Comment by rehrumesh** [comment]
LGTM. Open a PR with this

**Comment by lakindu95** [comment]
#117 @rehrumesh Opened a PR
