### ISSUE TITLE
stackle-app fails to serve on angular server

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [scorelab/Stackle#141]
## Type of issue:
- [x] Bug / Error
- [ ] Idea / Feature
- [ ] Improvement detail

## Short description on the issue
`stackle-app` angular build failing due to insufficient arguements in post service.

## Screenshots for the issue 

![screen shot 2018-08-22 at 12 07 47 pm](https://user-images.githubusercontent.com/29275810/44447054-92eebe80-a604-11e8-82b2-4de9791f283c.png)

**Comment by VibhorCodecianGupta** [comment]
@agentmilindu @psnmissaka please review #142 :)

**Comment by psnmissaka** [comment]
@VibhorCodecianGupta  this issue will be fixed in #140
