### ISSUE TITLE
UI Discrepancies

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [scorelab/Stackle#143]
## Type of issue:
- [x] Bug / Error
- [ ] Idea / Feature
- [x] Improvement detail

## Short description on the issue

- The **Profile** and **Logout** tabs on the nav-bar are aligned one below the other, they should appear beside each other.

- The **Issue** field is not getting cleared on clicking the `Clear` button (while creating a post).

- The image alignment in the nav-bar (the avatar image beside profile button) and in the stack images on the side-nav is broken, the image should appear in line with the identifiers.

- The **Common Feed** text on the feed page overflows out of view and wraps under the side-nav. The alignment needs to be fixed.

- The profile image of the user on the profile image would look better with a radius and a boundary around it.

- **Developed by SCoRE** is not visible because it is wrapped under the side-nav. It should preferably appear over the side-nav, at the very bottom.

- The picture beside the **Profile** tab should be the Github avatar of the user rather than a random picture.

## Possible fix
The corresponding PR fixes the issue

**Comment by VibhorCodecianGupta** [comment]
## Screenshots

![screen shot 2018-08-22 at 6 40 08 pm](https://user-images.githubusercontent.com/29275810/44617162-ae173380-a87b-11e8-9414-55718e2e8eed.png)

![screen shot 2018-08-23 at 7 44 44 pm](https://user-images.githubusercontent.com/29275810/44617167-bbccb900-a87b-11e8-8704-041c24677565.png)

**Comment by VibhorCodecianGupta** [comment]
#144 fixes this

@agentmilindu @psnmissaka please have a look :)

**Comment by psnmissaka** [comment]
@VibhorCodecianGupta  thanks for noticing the issue. Will be merging the #140 soon, once that is done you can update this PR and I will review
