### ISSUE TITLE
Dockers should have proper Label Schema labels

### ISSUE THREAD

**Issue by shravyanandyala** [scorelab/Stackle#20]
This repos has a Dockerfile but it does not contain any Label Schema labels.  Following are the lables we have to have on our Dockers. 
- [ ] `name` 
- [ ] `description` Shoud be on user's perspective.
- [ ] `url` Should be SCoRe website
- [ ] `vcs-url` Should point to GitHub repo
- [ ] `vcs-ref`
- [ ] `vendor` Shoudl be "SCoRe Lab"
- [ ] `version`
- [ ] `schema-version`

**Comment by shravyanandyala** [comment]
Working on it!

**Comment by agentmilindu** [comment]
Fixed by #21
