### ISSUE TITLE
Generate .gitignore using gitignore.io

### ISSUE THREAD

**Issue by TheLukaszNs** [scorelab/Stackle#23]
## What's the problem?
`.gitignore` files are not generated with [gitignore.io][1] 

## How can it be fixed?
I found two .gitignore (in `stackle_app/` and `stackle_api/`) files which should be generated with [gitignore.io][1]. Stackle is built on MEAN stack so I'll use this technology (**Node** for `_api` and **Angular** for `_app`) to generate new `.gitignore` files.

[1]: https://www.gitignore.io/

**Comment by agentmilindu** [comment]
I think since the `stackle_app` uses Bower, we have to include `bower` also.

**Comment by agentmilindu** [comment]
@TheLukaszNs You are good to go. Let's generate the `.gitignore` file with the above discussed technologies.
