### ISSUE TITLE
Views are not rendered properly

### ISSUE THREAD

**Issue by ntbandara3** [scorelab/Stackle#70]
Once the user logs in, the landing page view stays the same and navigating to profile or back to home does not do any change.

![screenshot from 2018-02-13 22-05-28](https://user-images.githubusercontent.com/14901805/36161781-8a638302-110a-11e8-91ce-55b79ddaf4b6.png)
![screenshot from 2018-02-13 22-05-44](https://user-images.githubusercontent.com/14901805/36161784-8bf03ecc-110a-11e8-90cc-d0e75bf7e000.png)

**Comment by ntbandara3** [comment]
I would like to work on this issue :)

**Comment by ntbandara3** [comment]
Added PR #72 :smiley:

**Comment by psnmissaka** [comment]
#72 merged
