### ISSUE TITLE
Navigation links are hidden when the page is reloaded when a session is active

### ISSUE THREAD

**Issue by ntbandara3** [scorelab/Stackle#86]
## Type of issue
- [x] Bug / Error
- [ ] Idea / Feature
- [ ] Improvment detail

## Short description on the issue
When reloading the page after a user is logged in, the navigation links to Home, Profile and the Logout is hidden even when the session is active.

## Possible fix
Recheck if the a session is active upon page reload.

**Comment by ntbandara3** [comment]
Created PR #87  :smile:

**Comment by psnmissaka** [comment]
Merged #87 that fixes the issue
